-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmUZY16HM7L8iE/ps
qPpRh7xEyEsscK6n9srAVAjnvnWgCgYIKoZIzj0DAQehRANCAARbjz7bL1BKpOcj
pRFurSIaT0ovcLuoXz8LDtx2TKS2GbxuP/bgow8s+UCHPvRZvyA9gwVeMTThBL9w
lndj6rN2
-----END PRIVATE KEY-----