name: Logo Test

on:
  workflow_dispatch:

jobs:
  logo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Node Kur
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dependencies Kur
        run: |
          npm install
          npm install axios
          npm install puppeteer
          npm install puppeteer-extra
          npm install puppeteer-extra-plugin-stealth

      - name: Logo Script Çalıştır
        run: |
          node logo_masters.js

      - name: Git Status
        id: verify
        run: |
          git status

          if [[ -n $(git status --porcelain) ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit & Push
        if: steps.verify.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "logo update"

          git push
