name: Mac Saati Veri Guncelleme

on:
  schedule:
    - cron: '0 6,8,10,12,14,16,18,20,22,0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev google-chrome-stable

      - name: Install Dependencies
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios

      - name: Fetch Matches
        run: node fetch.js

      - name: Fetch Logos (Only Midnight or Manual)
        if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        run: node fetch-logo.js

      - name: Degisiklikleri Kaydet ve Pushla
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Hata almamak için her şeyi ekliyoruz
          git add matches.json
          
          # Eğer logos klasörü varsa ve içinde png varsa ekle, yoksa hata verme
          if [ -d "logos" ]; then
            git add logos/*.png || echo "Yeni logo bulunamadı."
          fi
          
          git commit -m "Otomatik Guncelleme: $(date)" || echo "Degisiklik yok, commit edilmedi."
          git push
